{
 "title": "OracleDB Monitoring - performance and table space stats",
 "description": "Use oracledb exporter for oracle database monitoring. Compared with other dashboards, tablespace monitoring is added, which can be expanded to set tablespace alarms",
 "tags": [
  "prometheus",
  "oracle"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(oracledb_up, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 1 },
   "options": {
    "content": "# Custom Panel Summary\nCustom Panel - Realtime SQL\n- 실시간 SQL - 5초 Polling\n  - 현재 실행중인 SQL 문의 정보를 나타낸다. 5초마다 Polling 되어 Metric 을 수집한 시점의 정보를 실시간으로 노출한다.\n\nCustom Panel - Host CPU, Memory\n- Oracle DB 가 띄워진 HOST OS 의 CPU, Memory 사용량을 노출한다.\n\nCustom Panel - SQL쿼리별 CPU 사용시간 총량 기준 TOP 20 [5초마다 갱신]   (최하단에 있음)\n- SQL쿼리별 CPU 사용시간 총량 기준 TOP 20\n  - SQL 별 누적 총량으로 cpu_time TOP 20 에 대한 Metric 들을 노출한다.\n  - 당연히 실행 횟수가 많으면 CPU 사용시간도 높다.\n  - 실행 횟수가 비정상적으로 높거나, 실행 횟수가 낮음에도 CPU 사용시간이 높은 것을 중점적으로 보자.\n- SQL쿼리별 (총 수행시간 / 총 수행 수) TOP 20\n  - SQL 별 누적 총량으로 elapsed_time / executions 으로 TOP 20 에 대한 Metric 들을 노출한다.\n  - cpu_time 이 아닌 elasped_time 을 의미하므로 lock 대기, I/O 시간 등을 고려해야 한다.\n- SQL쿼리별 (Logical IO 수행 수 / SQL 실행 수) TOP 20\n  - SQL 별 누적 총량으로 buffer_gets / executions 으로 TOP 20 에 대한 Metric 들을 노출한다.\n  - disk_reads 에 비해 buffer_gets 값이 상대적으로 높다면 메모리에 캐싱이 되고 있는 것을 의미한다.\n  - 다만 buffer_gets / executions 값이 반드시 효율적이라기 보다는,  <br>\n  bugger_gets 값이 비정상적으로 높다면 Full Table Scan 자체가 캐싱되었을 가능성도 고려하자.\n\n<br>\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 9, "x": 7, "y": 1 },
   "options": {
    "content": "# Custom Panel Field\n\n- sid : 세션을 고유하게 식별하는 ID\n- serial# : 세션의 고유 시리얼 넘버. 세션 종료 후 재사용될 경우를 대비해 추가로 사용됨.\n- machine : 세션이 연결된 클라이언트의 host name\n- program : 세션을 시작한 application name (SQL*Plus, JDBC Driver...)\n- osuser : 세션을 실행 중인 클라이언트의 OS user name\n- elapsed_seconds : SQL 문이 실행된 지 경과한 시간 (unit : second)\n- sql_id : 실행 중인 SQL 문을 고유하게 식별하는 ID. 일반적으로 WHERE 절에 들어가는 바인딩 변수는 제외한 구문이다.\n- plan_hash_value : 실행 계획을 나타내는 Hash 값. 동일한 SQL 문이라도 바인딩 변수, 데이터 분포에 따라 인덱스 스캔이 다르게 된다. <br>\n세부적으로는 Buffer Cache, Shared Pool 등 메모리 사용량 및 SQL Hint, 파티셔닝, Curosr(커서) Sharing 등의 여부에 따라 변경될 수 있다.\n- executions: SQL 실행 수\n- buffer_gets: Logical I/O 수행 수 (많으면 인덱스 최적화)\n- disk_reads: Physical I/O 수행 수 (많으면 캐싱 / 데이터 접근 패턴 점검)\n- cpu_time: SQL 문이 실행 중 CPU 를 사용한 총 시간 (micro second)\n- elapsed_time: SQL 문이 실행을 완료하는 데 소요된 총 시간 (micro second). <br> \ncpu_time 뿐 아니라 I/O, Lock 대기, 컨텍스트 스위칭 등의 시간이 포함된다.\n- cpu_ratio: SQL 문이 총 CPU 자원에서 차지한 비율\n- elapsed_time_ratio: SQL 문이 전체 실행 시간(Elapsed Time)에서 차지한 비율\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "options": {
    "content": "# Tip\n\n<br>\n\n### 무한 Lock 으로 row 접근이 안되는 경우 <br> \nCustom Panel - Realtime SQL > 실시간 SQL - 5초 Polling 패널에서 문제가 되는 SQL 확인 후 <br>\n해당 SQL 의 sid, serial# 을 기준으로 <br>\n- ALTER SYSTEM KILL SESSION 'sid, serial#' IMMEDIATE; <br>\n\n을 실행해 해당 세션을 Kill 해 Lock 을 풀자.\n\n<br>\n\n### Custom Panel 의 Metric 조회 SQL 정보\n- Panel 명 옆의 i 툴팁 아이콘에 마우스를 올려놓으면 Metric 정보를 수집한 SQL 문 노출."
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "options": {
    "content": "metric collect reference : https://github.com/iamseth/oracledb_exporter <br>\ndashboard reference : https://grafana.com/grafana/dashboards/13555-oracledb-monitoring-performance-and-table-space-stats/"
   }
  },
  { "title": "Custom Panel - Realtime SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "실시간 SQL - 5초 Polling",
   "type": "table",
   "description": "SELECT\n    s.sid,\n    s.serial#,\n    s.status,\n    s.schemaname AS schema,\n    s.machine,\n    s.program,\n    s.osuser,\n    TO_CHAR(s.sql_exec_start, 'YYYY-MM-DD HH24:MI:SS') AS start_time,\n    ROUND((SYSDATE - s.sql_exec_start)*24*60*60, 0) AS elapsed_seconds,\n    s.sql_id,\n    q.hash_value AS plan_hash_value,\n    q.cpu_time,\n    q.buffer_gets,\n    q.disk_reads,\n    q.sql_text\nFROM v$session s\n         JOIN v$sqlarea q ON s.sql_id = q.sql_id\nWHERE s.status = 'ACTIVE'\n    AND s.sql_exec_start IS NOT NULL\n    AND s.schemaname != 'SYS'\nORDER BY q.cpu_time DESC;",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "oracledb_custom_sql_realtime_info_plan_hash_value{instance=\"$host\"}",
     "legendFormat": "realtime"
    }
   ]
  },
  {
   "title": "Custom Panel - Host CPU, Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "OS_CPU_USAGE_%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "oracledb_custom_os_resource_info_cpu_usage_percent{instance=\"$host\"}",
     "legendFormat": "cpu_usage_percent"
    }
   ]
  },
  {
   "title": "OS_MEMORY_USAGE_%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "oracledb_custom_os_resource_info_memory_usage_percent{instance=\"$host\"}",
     "legendFormat": "memory_usage_percent"
    }
   ]
  },
  {
   "title": "CURRENT_MEMORY",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_custom_os_resource_info_available_memory_gb{instance=\"$host\"}",
     "legendFormat": "useable_memory_gb"
    },
    {
     "expr": "oracledb_custom_os_resource_info_used_memory_gb{instance=\"$host\"}",
     "legendFormat": "used_memory_gb"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Database status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_up{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Process count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_process_count{instance=\"$host\"}",
     "legendFormat": "{{descr}} - Process count"
    }
   ]
  },
  {
   "title": "User commits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_user_commits{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Resource utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "oracledb_resource_current_utilization{instance=\"$host\"}",
     "legendFormat": "Resource utilization - {{resource_name}} "
    }
   ]
  },
  {
   "title": "Active sessions (USER)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_sessions_value{instance=\"$host\",type=\"USER\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Execute count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_activity_execute_count{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "User rollback",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_activity_user_rollbacks{instance=\"$host\"}",
     "legendFormat": "{{descr}} - User rollback"
    }
   ]
  },
  {
   "title": "Concurrent wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_concurrency{instance=\"$host\"}",
     "legendFormat": "{{descr}} - Concurrent wait time"
    }
   ]
  },
  {
   "title": "Commit wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_commit{instance=\"$host\"}",
     "legendFormat": "{{descr}} - Commit wait time"
    }
   ]
  },
  {
   "title": "Configure wait time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "oracledb_wait_time_configuration{instance=\"$host\"}",
     "legendFormat": "{{descr}} - Configure wait time"
    }
   ]
  },
  {
   "title": "Application wait time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_application{instance=\"$host\"}\t",
     "legendFormat": "{{descr}} - Application wait time"
    }
   ]
  },
  {
   "title": "Network wait time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_network{instance=\"$host\"}\t",
     "legendFormat": "{{descr}} - Network wait time"
    }
   ]
  },
  {
   "title": "Scheduler wait time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "oracledb_wait_time_scheduler{instance=\"$host\"}",
     "legendFormat": "{{descr}} - Scheduler wait time"
    }
   ]
  },
  {
   "title": "System I/O wait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_system_io{instance=\"$host\"}",
     "legendFormat": "{{descr}} - System I/O wait"
    }
   ]
  },
  {
   "title": "User I/O wait",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_user_io{instance=\"$host\"}\t",
     "legendFormat": "{{descr}} - User I/O wait"
    }
   ]
  },
  { "title": "Performance collector status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Total collection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_exporter_scrapes_total{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Final collection time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_exporter_last_scrape_duration_seconds{instance=\"$host\"}\t"
    }
   ]
  },
  {
   "title": "Custom Panel - SQL쿼리별 CPU 사용시간 총량 기준 TOP 20 [5초마다 갱신]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 }
  },
  {
   "title": "SQL쿼리별 CPU 사용시간 총량 기준 TOP 20",
   "type": "table",
   "description": "SELECT main.*, (SELECT rtrim(xmlagg(xmlelement(e, sql_text ,' ').extract('//text()') order by piece).GetClobVal(),' ') FROM v$sqltext b WHERE b.sql_id = main.sql_id GROUP BY sql_id ) as full_txt, (SELECT rtrim(xmlagg(xmlelement(e,name || ' = ' || nvl(value_string,'NULL'),' / ').extract('//text()') order by sql_id).GetClobVal(),' / ') FROM V$SQL_BIND_CAPTURE c WHERE c.was_captured = 'YES' AND c.sql_id = main.sql_id AND (sql_id , last_captured) IN (SELECT sql_id , max(last_captured) as last_captured FROM V$SQL_BIND_CAPTURE d WHERE was_captured = 'YES' AND d.sql_id = main.sql_id GROUP BY sql_id ) GROUP BY sql_id ) as bind_vals FROM ( SELECT sql_id, plan_hash_value, parsing_schema_name, executions, buffer_gets, disk_reads, cpu_time, elapsed_time, round(cpu_time/sum(cpu_time) OVER()*100,1) cpu_ratio, round(elapsed_time/sum(elapsed_time) OVER () *100 ,1) elapsed_time_ratio FROM v$sqlarea a WHERE executions > 1 AND parsing_schema_name not in ('SYSAUX','SYSMAN','XDB','HR','ODM','OUTLN','OE','SH','PM','IX','WK_TEST','PERFSTAT','DBSNMP','OLAPSYS','QS_CS','QS_CB','QS_CBADM','QS_OS','QS_WS','QS','QS_ADM','ODM_MTR','WKPROXY','QS_ES','ANONYMOUS','WKSYS','WMSYS','APEX_030200','APEX_PUBLIC_USER','APPQOSSYS','BI','CTXSYS','DIP','EXFSYS','FLOWS_FILES','MDDATA','MDSYS','MGMT_VIEW','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OWBSYS','OWBSYS_AUDIT','SCOTT','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','XS$NULL') AND NOT (module LIKE 'Golden%' OR module LIKE 'TOAD%' OR module LIKE 'toad%' OR module LIKE 'Orange%' OR module LIKE 'exp%' OR module LIKE 'SQL*Plus%' OR module LIKE 'SQL Developer%' OR module LIKE 'oracle@%' OR module LIKE 'sqlplus@%') AND NOT (TRIM(SQL_TEXT) LIKE '%:Q%' OR TRIM(SQL_TEXT) LIKE 'declare%' OR TRIM(SQL_TEXT) LIKE 'DECLARE%' OR TRIM(SQL_TEXT) LIKE 'truncate%' OR TRIM(SQL_TEXT) LIKE 'TRUNCATE%' OR TRIM(SQL_TEXT) LIKE '%dba\\_%' escape '\\\\' OR TRIM(SQL_TEXT) LIKE '%DBA\\_%' escape '\\\\' OR TRIM(SQL_TEXT) LIKE 'SQLGateMain%' OR TRIM(SQL_TEXT) LIKE 'ALTER SESSION%' OR TRIM(SQL_TEXT) LIKE '%v$%' OR TRIM(SQL_TEXT) LIKE '%x$%') ORDER BY cpu_time/sum(cpu_time) OVER()*100 desc ) main WHERE rownum <= 20",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oracledb_custom_sql_accumulate_cpu_use_avg_top_20_plan_hash_value{instance=\"$host\"}",
     "legendFormat": "cpu_use_avg_top_20"
    }
   ]
  },
  {
   "title": "Custom Panel - SQL쿼리별 (총 수행시간 / 총 수행 수) TOP 20 [5초마다 갱신]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 }
  },
  {
   "title": "SQL쿼리별 (총 수행시간 / 총 수행 수) TOP 20",
   "type": "table",
   "description": "SELECT main.*, (SELECT rtrim(xmlagg(xmlelement(e, sql_text ,' ').extract('//text()') order by piece).GetClobVal(),' ') FROM v$sqltext b WHERE b.sql_id = main.sql_id GROUP BY sql_id ) as full_txt, (SELECT rtrim(xmlagg(xmlelement(e,name || ' = ' || nvl(value_string,'NULL'),' / ').extract('//text()') order by sql_id).GetClobVal(),' / ') FROM V$SQL_BIND_CAPTURE c WHERE c.was_captured = 'YES' AND c.sql_id = main.sql_id AND (sql_id , last_captured) IN (SELECT sql_id , max(last_captured) as last_captured FROM V$SQL_BIND_CAPTURE d WHERE was_captured = 'YES' AND d.sql_id = main.sql_id GROUP BY sql_id ) GROUP BY sql_id ) as bind_vals FROM ( SELECT sql_id, plan_hash_value, parsing_schema_name, executions, buffer_gets, disk_reads, cpu_time, elapsed_time, round(cpu_time/sum(cpu_time) OVER()*100,1) cpu_ratio, round(elapsed_time/sum(elapsed_time) OVER () *100 ,1) elapsed_time_ratio FROM v$sqlarea a WHERE executions > 1 AND parsing_schema_name not in ('SYSAUX','SYSMAN','XDB','HR','ODM','OUTLN','OE','SH','PM','IX','WK_TEST','PERFSTAT','DBSNMP','OLAPSYS','QS_CS','QS_CB','QS_CBADM','QS_OS','QS_WS','QS','QS_ADM','ODM_MTR','WKPROXY','QS_ES','ANONYMOUS','WKSYS','WMSYS','APEX_030200','APEX_PUBLIC_USER','APPQOSSYS','BI','CTXSYS','DIP','EXFSYS','FLOWS_FILES','MDDATA','MDSYS','MGMT_VIEW','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OWBSYS','OWBSYS_AUDIT','SCOTT','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','XS$NULL') AND NOT (module LIKE 'Golden%' OR module LIKE 'TOAD%' OR module LIKE 'toad%' OR module LIKE 'Orange%' OR module LIKE 'exp%' OR module LIKE 'SQL*Plus%' OR module LIKE 'SQL Developer%' OR module LIKE 'oracle@%' OR module LIKE 'sqlplus@%') AND NOT (TRIM(SQL_TEXT) LIKE '%:Q%' OR TRIM(SQL_TEXT) LIKE 'declare%' OR TRIM(SQL_TEXT) LIKE 'DECLARE%' OR TRIM(SQL_TEXT) LIKE 'truncate%' OR TRIM(SQL_TEXT) LIKE 'TRUNCATE%' OR TRIM(SQL_TEXT) LIKE '%dba\\_%' escape '\\\\' OR TRIM(SQL_TEXT) LIKE '%DBA\\_%' escape '\\\\' OR TRIM(SQL_TEXT) LIKE 'SQLGateMain%' OR TRIM(SQL_TEXT) LIKE 'ALTER SESSION%' OR TRIM(SQL_TEXT) LIKE '%v$%' OR TRIM(SQL_TEXT) LIKE '%x$%') ORDER BY cpu_time/sum(cpu_time) OVER()*100 desc ) main WHERE rownum <= 20",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oracledb_custom_sql_accumulate_elapsed_avg_top_20_plan_hash_value{instance=\"$host\"}",
     "legendFormat": "elapsed_avg_top_20"
    }
   ]
  },
  {
   "title": "Custom Panel - SQL쿼리별 (Logical IO 수행 수 / SQL 실행 수) TOP 20 [5초마다 갱신]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 }
  },
  {
   "title": "SQL쿼리별 (Logical IO 수행 수 / SQL 실행 수) TOP 20",
   "type": "table",
   "description": "SELECT main.*, (SELECT rtrim(xmlagg(xmlelement(e, sql_text ,' ').extract('//text()') order by piece).GetClobVal(),' ') FROM v$sqltext b WHERE b.sql_id = main.sql_id GROUP BY sql_id ) as full_txt, (SELECT rtrim(xmlagg(xmlelement(e,name || ' = ' || nvl(value_string,'NULL'),' / ').extract('//text()') order by sql_id).GetClobVal(),' / ') FROM V$SQL_BIND_CAPTURE c WHERE c.was_captured = 'YES' AND c.sql_id = main.sql_id AND (sql_id , last_captured) IN (SELECT sql_id , max(last_captured) as last_captured FROM V$SQL_BIND_CAPTURE d WHERE was_captured = 'YES' AND d.sql_id = main.sql_id GROUP BY sql_id ) GROUP BY sql_id ) as bind_vals FROM ( SELECT sql_id, plan_hash_value, parsing_schema_name, executions, buffer_gets, disk_reads, cpu_time, elapsed_time, round(cpu_time/sum(cpu_time) OVER()*100,1) cpu_ratio, round(elapsed_time/sum(elapsed_time) OVER () *100 ,1) elapsed_time_ratio FROM v$sqlarea a WHERE executions > 1 AND parsing_schema_name not in ('SYSAUX','SYSMAN','XDB','HR','ODM','OUTLN','OE','SH','PM','IX','WK_TEST','PERFSTAT','DBSNMP','OLAPSYS','QS_CS','QS_CB','QS_CBADM','QS_OS','QS_WS','QS','QS_ADM','ODM_MTR','WKPROXY','QS_ES','ANONYMOUS','WKSYS','WMSYS','APEX_030200','APEX_PUBLIC_USER','APPQOSSYS','BI','CTXSYS','DIP','EXFSYS','FLOWS_FILES','MDDATA','MDSYS','MGMT_VIEW','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','OWBSYS','OWBSYS_AUDIT','SCOTT','SI_INFORMTN_SCHEMA','SPATIAL_CSW_ADMIN_USR','SPATIAL_WFS_ADMIN_USR','XS$NULL') AND NOT (module LIKE 'Golden%' OR module LIKE 'TOAD%' OR module LIKE 'toad%' OR module LIKE 'Orange%' OR module LIKE 'exp%' OR module LIKE 'SQL*Plus%' OR module LIKE 'SQL Developer%' OR module LIKE 'oracle@%' OR module LIKE 'sqlplus@%') AND NOT (TRIM(SQL_TEXT) LIKE '%:Q%' OR TRIM(SQL_TEXT) LIKE 'declare%' OR TRIM(SQL_TEXT) LIKE 'DECLARE%' OR TRIM(SQL_TEXT) LIKE 'truncate%' OR TRIM(SQL_TEXT) LIKE 'TRUNCATE%' OR TRIM(SQL_TEXT) LIKE '%dba\\_%' escape '\\\\' OR TRIM(SQL_TEXT) LIKE '%DBA\\_%' escape '\\\\' OR TRIM(SQL_TEXT) LIKE 'SQLGateMain%' OR TRIM(SQL_TEXT) LIKE 'ALTER SESSION%' OR TRIM(SQL_TEXT) LIKE '%v$%' OR TRIM(SQL_TEXT) LIKE '%x$%') ORDER BY cpu_time/sum(cpu_time) OVER()*100 desc ) main WHERE rownum <= 20",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oracledb_custom_sql_accumulate_logical_reads_avg_top_20_plan_hash_value{instance=\"$host\"}",
     "legendFormat": "logical_reads_avg_top_20"
    }
   ]
  }
 ]
}